# Generated by Django 5.2.7 on 2025-12-06 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_sq', models.CharField(blank=True, help_text='Name in Albanian', max_length=100)),
                ('name_it', models.CharField(blank=True, help_text='Name in Italian', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title in English', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings', max_length=500)),
                ('content', models.TextField(help_text='Full blog content in English')),
                ('title_sq', models.CharField(blank=True, help_text='Title in Albanian', max_length=255)),
                ('excerpt_sq', models.TextField(blank=True, help_text='Excerpt in Albanian', max_length=500)),
                ('content_sq', models.TextField(blank=True, help_text='Content in Albanian')),
                ('title_it', models.CharField(blank=True, help_text='Title in Italian', max_length=255)),
                ('excerpt_it', models.TextField(blank=True, help_text='Excerpt in Italian', max_length=500)),
                ('content_it', models.TextField(blank=True, help_text='Content in Italian')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='blog/images/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for image', max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('author', models.CharField(default='MSC Certifications', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx')],
            },
        ),
    ]
