# Generated by Django 5.2.7 on 2025-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_it',
            field=models.SlugField(blank=True, help_text='URL slug in Italian', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_sq',
            field=models.SlugField(blank=True, help_text='URL slug in Albanian', max_length=255),
        ),
    ]
