# Generated by Django 5.2.7 on 2025-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_translated_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_static',
            field=models.CharField(blank=True, help_text='Static image path (e.g., /images/blog.jpeg) for seeded content', max_length=255),
        ),
    ]
