# Generated by Django 5.2.7 on 2025-11-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, help_text='Unique certificate number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid/Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='VALID', max_length=20)),
                ('standard', models.CharField(choices=[('ISO_9001_2015', 'ISO 9001:2015'), ('ISO_14001_2015', 'ISO 14001:2015'), ('ISO_22000_2018', 'ISO 22000:2018'), ('ISO_27001_2022', 'ISO 27001:2022'), ('ISO_37001_2025', 'ISO 37001:2025'), ('ISO_39001_2012', 'ISO 39001:2012'), ('ISO_45001_2023', 'ISO 45001:2023'), ('HACCP', 'HACCP: Hazard Analysis and Critical Control Points')], help_text='ISO Standard or certification type', max_length=20)),
                ('company_name', models.CharField(help_text='Name of the certified company', max_length=255)),
                ('first_issue_date', models.DateField(help_text='Date when certificate was first issued')),
                ('expiry_date', models.DateField(help_text='Certificate expiration date')),
                ('scope_activity', models.TextField(help_text='Scope of certification or business activity')),
                ('iaf_code', models.CharField(help_text='IAF (International Accreditation Forum) code', max_length=50)),
                ('next_maintenance_date', models.DateField(help_text='Next scheduled maintenance date (annual)')),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificate_qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.PositiveIntegerField(help_text='Site sequence number')),
                ('name', models.CharField(help_text='Site/location name', max_length=255)),
                ('scope_activity', models.TextField(help_text='Scope of activities at this site')),
                ('address', models.TextField(help_text='Complete address of the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Site',
                'verbose_name_plural': 'Certificate Sites',
                'ordering': ['certificate', 'site_number'],
                'unique_together': {('certificate', 'site_number')},
            },
        ),
    ]
