# Generated by Django 5.2.7 on 2025-11-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_secure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='next_maintenance_date',
            field=models.DateField(blank=True, help_text='Next scheduled maintenance date (annual). Auto-calculated if not provided.', null=True),
        ),
    ]
