# Generated by Django 5.2.7 on 2025-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_allow_null_next_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(help_text='Unique certificate number (e.g., MSC/ISO9001/2024/001)', max_length=100, unique=True),
        ),
    ]
