# Generated by Django 5.2.7 on 2026-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_add_iso22301_and_iso50001_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='address',
            field=models.TextField(blank=True, help_text='Company address shown on certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='modification_date',
            field=models.DateField(blank=True, help_text='Data e Modifikimit - modification date shown on certificate', null=True),
        ),
    ]
