# Generated by Django 5.2.7 on 2026-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificate_address_certificate_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload signature image (PNG with transparent background recommended)', null=True, upload_to='certificate_signatures/'),
        ),
    ]
