# Generated by Django 5.2.7 on 2026-09-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Optional link to the company directory (powers the admin autocomplete). Leave blank for existing certificates -- it has no effect on what's displayed or on the QR code.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.company'),
        ),
    ]
