# Generated by Django 5.2.7 on 2025-12-06 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('title_sq', models.CharField(blank=True, help_text='Section title in Albanian', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Section description/instructions')),
                ('description_sq', models.TextField(blank=True, help_text='Section description in Albanian')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['form_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_email', models.EmailField(help_text='Email of the person submitting the form', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('submitter_name', models.CharField(help_text='Name of the submitter', max_length=255)),
                ('submitter_phone', models.CharField(blank=True, help_text='Phone number', max_length=50)),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=255)),
                ('submission_number', models.CharField(editable=False, help_text='Auto-generated submission reference number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to submitter)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Form name (e.g., 'ISO 9001 Initial Assessment')", max_length=255)),
                ('name_sq', models.CharField(blank=True, help_text='Form name in Albanian', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Form description')),
                ('description_sq', models.TextField(blank=True, help_text='Form description in Albanian')),
                ('iso_standard', models.CharField(choices=[('ISO_9001', 'ISO 9001:2015 - Quality Management'), ('ISO_14001', 'ISO 14001:2015 - Environmental Management'), ('ISO_22000', 'ISO 22000:2018 - Food Safety'), ('ISO_22301', 'ISO 22301:2019 - Business Continuity'), ('ISO_27001', 'ISO 27001:2022 - Information Security'), ('ISO_37001', 'ISO 37001:2016 - Anti-Bribery'), ('ISO_39001', 'ISO 39001:2012 - Road Traffic Safety'), ('ISO_45001', 'ISO 45001:2018 - Occupational Health & Safety'), ('ISO_50001', 'ISO 50001:2018 - Energy Management'), ('HACCP', 'HACCP - Food Safety'), ('GENERAL', 'General Inquiry')], db_index=True, help_text='ISO standard this form is for', max_length=20)),
                ('form_type', models.CharField(default='assessment', help_text='Type of form (assessment, application, feedback, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this form is currently accepting submissions')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this form is visible to public users')),
                ('requires_auth', models.BooleanField(default=False, help_text='Whether user must be logged in to submit')),
                ('allow_multiple_submissions', models.BooleanField(default=True, help_text='Allow same email to submit multiple times')),
                ('send_confirmation_email', models.BooleanField(default=True, help_text='Send confirmation email after submission')),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated email addresses to notify on new submissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'ordering': ['iso_standard', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_text_sq', models.TextField(blank=True, help_text='Question text in Albanian')),
                ('help_text', models.TextField(blank=True, help_text='Additional help/instructions for the question')),
                ('help_text_sq', models.TextField(blank=True, help_text='Help text in Albanian')),
                ('question_type', models.CharField(choices=[('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text'), ('EMAIL', 'Email Address'), ('PHONE', 'Phone Number'), ('NUMBER', 'Number'), ('SELECT', 'Single Choice (Dropdown)'), ('RADIO', 'Single Choice (Radio)'), ('CHECKBOX', 'Multiple Choice (Checkbox)'), ('DATE', 'Date'), ('FILE', 'File Upload'), ('HEADING', 'Section Heading (Display Only)')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this question must be answered')),
                ('options', models.JSONField(blank=True, help_text='Options for choice-type questions (JSON array)', null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules (JSON object)', null=True)),
                ('conditional_logic', models.JSONField(blank=True, help_text='Show this question only if condition is met', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within section')),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formsection')),
            ],
            options={
                'verbose_name': 'Form Question',
                'verbose_name_plural': 'Form Questions',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(blank=True, help_text='User who made the change', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Submission Log',
                'verbose_name_plural': 'Submission Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formtemplate'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, help_text='Text answer')),
                ('answer_json', models.JSONField(blank=True, help_text='JSON answer for complex types (checkboxes, etc.)', null=True)),
                ('answer_file', models.FileField(blank=True, help_text='Uploaded file', null=True, upload_to='form_uploads/%Y/%m/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='forms.formquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Form Answer',
                'verbose_name_plural': 'Form Answers',
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['submitter_email'], name='forms_forms_submitt_0695a6_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['submission_number'], name='forms_forms_submiss_a01a16_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='forms_forms_status_107ef7_idx'),
        ),
    ]
