# Generated by Django 5.2.7 on 2025-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='help_text_it',
            field=models.TextField(blank=True, help_text='Help text in Italian'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='question_text_it',
            field=models.TextField(blank=True, help_text='Question text in Italian'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='description_it',
            field=models.TextField(blank=True, help_text='Section description in Italian'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='title_it',
            field=models.CharField(blank=True, help_text='Section title in Italian', max_length=255),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='description_it',
            field=models.TextField(blank=True, help_text='Form description in Italian'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='name_it',
            field=models.CharField(blank=True, help_text='Form name in Italian', max_length=255),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this question must be answered'),
        ),
    ]
